<?php

namespace Database\Seeders;

use App\Models\PlanCuenta;
use Illuminate\Database\Seeder;

class PlanCuentaSeeder extends Seeder
{
    public function run(): void
    {
        $cuentas = $this->getCuentas();

        // Primer paso: crear todas las cuentas sin padre_id
        $creadas = [];
        foreach ($cuentas as $data) {
            $cuenta = PlanCuenta::firstOrCreate(
                ['codigo' => $data['codigo']],
                [
                    'nombre'           => $data['nombre'],
                    'tipo'             => $data['tipo'],
                    'nivel'            => $data['nivel'],
                    'padre_id'         => null,
                    'permite_asientos' => $data['asientos'],
                    'estado'           => true,
                    'total_asientos'   => 0,
                ]
            );
            $creadas[$data['codigo']] = $cuenta->id;
        }

        // Segundo paso: asignar padre_id
        foreach ($cuentas as $data) {
            if (!empty($data['padre']) && isset($creadas[$data['padre']])) {
                PlanCuenta::where('codigo', $data['codigo'])->update([
                    'padre_id' => $creadas[$data['padre']],
                ]);
            }
        }
    }

    private function getCuentas(): array
    {
        return [
            // ── ACTIVOS ──────────────────────────────────────────────────────────
            ['codigo'=>'1',          'nombre'=>'ACTIVOS',                                    'tipo'=>'activo',     'nivel'=>1, 'padre'=>null,        'asientos'=>false],
            ['codigo'=>'1.1',        'nombre'=>'ACTIVO CORRIENTE',                           'tipo'=>'activo',     'nivel'=>2, 'padre'=>'1',          'asientos'=>false],
            ['codigo'=>'1.1.1',      'nombre'=>'Efectivo y Equivalentes al Efectivo',        'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.1',        'asientos'=>false],
            ['codigo'=>'1.1.1.1',    'nombre'=>'Caja General',                               'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.1',      'asientos'=>true],
            ['codigo'=>'1.1.1.2',    'nombre'=>'Cajas Chicas y Fondos',                      'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.1',      'asientos'=>true],
            ['codigo'=>'1.1.1.3',    'nombre'=>'Bancos Locales',                             'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.1',      'asientos'=>true],
            ['codigo'=>'1.1.1.4',    'nombre'=>'Bancos del Exterior',                        'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.1',      'asientos'=>true],
            ['codigo'=>'1.1.1.5',    'nombre'=>'Dinero Electronico / Pasarelas de Pago',     'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.1',      'asientos'=>true],
            ['codigo'=>'1.1.2',      'nombre'=>'Inversiones Financieras a Corto Plazo',      'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.1',        'asientos'=>false],
            ['codigo'=>'1.1.2.1',    'nombre'=>'Inversiones a Costo Amortizado (Polizas)',   'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.2',      'asientos'=>true],
            ['codigo'=>'1.1.3',      'nombre'=>'Cuentas y Documentos por Cobrar',            'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.1',        'asientos'=>false],
            ['codigo'=>'1.1.3.1',    'nombre'=>'Clientes Locales',                           'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.3',      'asientos'=>true],
            ['codigo'=>'1.1.3.2',    'nombre'=>'Clientes del Exterior',                      'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.3',      'asientos'=>true],
            ['codigo'=>'1.1.3.3',    'nombre'=>'Anticipos a Proveedores',                    'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.3',      'asientos'=>true],
            ['codigo'=>'1.1.3.4',    'nombre'=>'Prestamos y Anticipos a Empleados',          'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.3',      'asientos'=>true],
            ['codigo'=>'1.1.3.5',    'nombre'=>'(-) Provision Cuentas Incobrables',          'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.3',      'asientos'=>true],
            ['codigo'=>'1.1.4',      'nombre'=>'Inventarios',                                'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.1',        'asientos'=>false],
            ['codigo'=>'1.1.4.1',    'nombre'=>'Inventario de Mercaderia',                   'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.4',      'asientos'=>true],
            ['codigo'=>'1.1.4.2',    'nombre'=>'Inventario de Materia Prima y Suministros',  'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.4',      'asientos'=>true],
            ['codigo'=>'1.1.4.3',    'nombre'=>'Inventario en Transito',                     'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.4',      'asientos'=>true],
            ['codigo'=>'1.1.4.4',    'nombre'=>'(-) Provision por Deterioro de Inventarios', 'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.4',      'asientos'=>true],
            ['codigo'=>'1.1.5',      'nombre'=>'Activos por Impuestos Corrientes',           'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.1',        'asientos'=>false],
            ['codigo'=>'1.1.5.1',    'nombre'=>'Credito Tributario por IVA',                 'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.5',      'asientos'=>true],
            ['codigo'=>'1.1.5.2',    'nombre'=>'Credito Tributario por Retenciones de IVA',  'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.5',      'asientos'=>true],
            ['codigo'=>'1.1.5.3',    'nombre'=>'Credito Tributario por Retenciones de IR',   'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.5',      'asientos'=>true],
            ['codigo'=>'1.1.5.4',    'nombre'=>'Anticipo de Impuesto a la Renta',            'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.5',      'asientos'=>true],
            ['codigo'=>'1.1.6',      'nombre'=>'Gastos Pagados por Anticipado',              'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.1',        'asientos'=>false],
            ['codigo'=>'1.1.6.1',    'nombre'=>'Seguros Pagados por Anticipado',             'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.6',      'asientos'=>true],
            ['codigo'=>'1.1.6.2',    'nombre'=>'Arriendos Pagados por Anticipado',           'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.1.6',      'asientos'=>true],
            ['codigo'=>'1.1.7',      'nombre'=>'Otros Activos Corrientes',                   'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.1',        'asientos'=>true],
            ['codigo'=>'1.2',        'nombre'=>'ACTIVO NO CORRIENTE',                        'tipo'=>'activo',     'nivel'=>2, 'padre'=>'1',          'asientos'=>false],
            ['codigo'=>'1.2.1',      'nombre'=>'Propiedades, Planta y Equipo',               'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.2',        'asientos'=>false],
            ['codigo'=>'1.2.1.1',    'nombre'=>'Terrenos',                                   'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.2',    'nombre'=>'Edificios',                                  'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.3',    'nombre'=>'Instalaciones',                              'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.4',    'nombre'=>'Muebles y Enseres',                          'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.5',    'nombre'=>'Maquinaria y Equipos',                       'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.6',    'nombre'=>'Equipos de Computacion',                     'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.7',    'nombre'=>'Vehiculos y Equipos de Transporte',          'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.8',    'nombre'=>'Repuestos y Herramientas',                   'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.9',    'nombre'=>'Construcciones en Curso',                    'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.1.10',   'nombre'=>'(-) Depreciacion Acumulada PPE',             'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>false],
            ['codigo'=>'1.2.1.10.1', 'nombre'=>'(-) Dep. Acum. Edificios',                   'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1.10',   'asientos'=>true],
            ['codigo'=>'1.2.1.10.2', 'nombre'=>'(-) Dep. Acum. Instalaciones',               'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1.10',   'asientos'=>true],
            ['codigo'=>'1.2.1.10.3', 'nombre'=>'(-) Dep. Acum. Muebles y Enseres',           'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1.10',   'asientos'=>true],
            ['codigo'=>'1.2.1.10.4', 'nombre'=>'(-) Dep. Acum. Maquinaria',                  'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1.10',   'asientos'=>true],
            ['codigo'=>'1.2.1.10.5', 'nombre'=>'(-) Dep. Acum. Equipos Computacion',         'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1.10',   'asientos'=>true],
            ['codigo'=>'1.2.1.10.6', 'nombre'=>'(-) Dep. Acum. Vehiculos',                   'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1.10',   'asientos'=>true],
            ['codigo'=>'1.2.1.11',   'nombre'=>'(-) Deterioro Acumulado PPE',                'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.1',      'asientos'=>true],
            ['codigo'=>'1.2.2',      'nombre'=>'Propiedades de Inversion',                   'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.2',        'asientos'=>false],
            ['codigo'=>'1.2.2.1',    'nombre'=>'Terrenos (Inversion)',                       'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.2',      'asientos'=>true],
            ['codigo'=>'1.2.2.2',    'nombre'=>'Edificios (Inversion)',                      'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.2',      'asientos'=>true],
            ['codigo'=>'1.2.2.3',    'nombre'=>'(-) Depreciacion Acumulada Inv.',            'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.2',      'asientos'=>true],
            ['codigo'=>'1.2.3',      'nombre'=>'Activos Intangibles',                        'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.2',        'asientos'=>false],
            ['codigo'=>'1.2.3.1',    'nombre'=>'Software y Licencias',                       'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.3',      'asientos'=>true],
            ['codigo'=>'1.2.3.2',    'nombre'=>'Marcas y Patentes',                          'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.3',      'asientos'=>true],
            ['codigo'=>'1.2.3.3',    'nombre'=>'(-) Amortizacion Acumulada Intangibles',     'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.3',      'asientos'=>true],
            ['codigo'=>'1.2.4',      'nombre'=>'Activos por Impuestos Diferidos',            'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.2',        'asientos'=>false],
            ['codigo'=>'1.2.4.1',    'nombre'=>'Activo por Impuesto Diferido',               'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.4',      'asientos'=>true],
            ['codigo'=>'1.2.5',      'nombre'=>'Activos Financieros a Largo Plazo',          'tipo'=>'activo',     'nivel'=>3, 'padre'=>'1.2',        'asientos'=>false],
            ['codigo'=>'1.2.5.1',    'nombre'=>'Cuentas y Documentos por Cobrar LP',         'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.5',      'asientos'=>true],
            ['codigo'=>'1.2.5.2',    'nombre'=>'Inversiones a Costo Amortizado LP',          'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.5',      'asientos'=>true],
            ['codigo'=>'1.2.5.3',    'nombre'=>'(-) Provision Cuentas Incobrables LP',       'tipo'=>'activo',     'nivel'=>4, 'padre'=>'1.2.5',      'asientos'=>true],

            // ── PASIVOS ──────────────────────────────────────────────────────────
            ['codigo'=>'2',          'nombre'=>'PASIVOS',                                    'tipo'=>'pasivo',     'nivel'=>1, 'padre'=>null,        'asientos'=>false],
            ['codigo'=>'2.1',        'nombre'=>'PASIVO CORRIENTE',                           'tipo'=>'pasivo',     'nivel'=>2, 'padre'=>'2',          'asientos'=>false],
            ['codigo'=>'2.1.1',      'nombre'=>'Cuentas y Documentos por Pagar',             'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.1',        'asientos'=>false],
            ['codigo'=>'2.1.1.1',    'nombre'=>'Proveedores Locales',                        'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.1',      'asientos'=>true],
            ['codigo'=>'2.1.1.2',    'nombre'=>'Proveedores del Exterior',                   'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.1',      'asientos'=>true],
            ['codigo'=>'2.1.1.3',    'nombre'=>'Anticipos de Clientes',                      'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.1',      'asientos'=>true],
            ['codigo'=>'2.1.2',      'nombre'=>'Obligaciones con Instituciones Financieras', 'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.1',        'asientos'=>false],
            ['codigo'=>'2.1.2.1',    'nombre'=>'Prestamos Bancarios a Corto Plazo',          'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.2',      'asientos'=>true],
            ['codigo'=>'2.1.2.2',    'nombre'=>'Tarjetas de Credito Corporativas',           'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.2',      'asientos'=>true],
            ['codigo'=>'2.1.3',      'nombre'=>'Obligaciones Tributarias SRI',               'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.1',        'asientos'=>false],
            ['codigo'=>'2.1.3.1',    'nombre'=>'Retenciones en la Fuente de IR por Pagar',   'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.3',      'asientos'=>true],
            ['codigo'=>'2.1.3.2',    'nombre'=>'Retenciones de IVA por Pagar',               'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.3',      'asientos'=>true],
            ['codigo'=>'2.1.3.3',    'nombre'=>'Impuesto a la Renta por Pagar',              'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.3',      'asientos'=>true],
            ['codigo'=>'2.1.3.4',    'nombre'=>'IVA Ventas por Pagar',                       'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.3',      'asientos'=>true],
            ['codigo'=>'2.1.4',      'nombre'=>'Obligaciones Laborales y Sociales',          'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.1',        'asientos'=>false],
            ['codigo'=>'2.1.4.1',    'nombre'=>'Nomina por Pagar',                           'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.4.2',    'nombre'=>'Obligaciones IESS Aporte Patronal 11.15%',   'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.4.3',    'nombre'=>'Obligaciones IESS Aporte Personal 9.45%',    'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.4.4',    'nombre'=>'Obligaciones IESS Prestamos',                'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.4.5',    'nombre'=>'Decimo Tercer Sueldo por Pagar',             'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.4.6',    'nombre'=>'Decimo Cuarto Sueldo por Pagar',             'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.4.7',    'nombre'=>'Vacaciones por Pagar',                       'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.4.8',    'nombre'=>'Fondos de Reserva por Pagar',                'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.4.9',    'nombre'=>'Utilidades a Trabajadores 15% por Pagar',    'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.4',      'asientos'=>true],
            ['codigo'=>'2.1.5',      'nombre'=>'Obligaciones con Accionistas',               'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.1',        'asientos'=>false],
            ['codigo'=>'2.1.5.1',    'nombre'=>'Prestamos de Accionistas CP',                'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.5',      'asientos'=>true],
            ['codigo'=>'2.1.5.2',    'nombre'=>'Dividendos por Pagar',                       'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.5',      'asientos'=>true],
            ['codigo'=>'2.1.6',      'nombre'=>'Otros Pasivos Corrientes',                   'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.1',        'asientos'=>false],
            ['codigo'=>'2.1.6.1',    'nombre'=>'Porcion Corriente de Obligaciones LP',       'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.6',      'asientos'=>true],
            ['codigo'=>'2.1.6.2',    'nombre'=>'Provisiones a Corto Plazo',                  'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.1.6',      'asientos'=>true],
            ['codigo'=>'2.2',        'nombre'=>'PASIVO NO CORRIENTE',                        'tipo'=>'pasivo',     'nivel'=>2, 'padre'=>'2',          'asientos'=>false],
            ['codigo'=>'2.2.1',      'nombre'=>'Cuentas y Documentos por Pagar LP',          'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.2',        'asientos'=>false],
            ['codigo'=>'2.2.1.1',    'nombre'=>'Proveedores Locales LP',                     'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.1',      'asientos'=>true],
            ['codigo'=>'2.2.1.2',    'nombre'=>'Proveedores del Exterior LP',                'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.1',      'asientos'=>true],
            ['codigo'=>'2.2.1.3',    'nombre'=>'Documentos / Letras por Pagar LP',           'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.1',      'asientos'=>true],
            ['codigo'=>'2.2.2',      'nombre'=>'Obligaciones Financieras LP',                'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.2',        'asientos'=>false],
            ['codigo'=>'2.2.2.1',    'nombre'=>'Prestamos Bancarios LP',                     'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.2',      'asientos'=>true],
            ['codigo'=>'2.2.3',      'nombre'=>'Anticipos a Largo Plazo',                    'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.2',        'asientos'=>false],
            ['codigo'=>'2.2.3.1',    'nombre'=>'Anticipos de Clientes LP',                   'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.3',      'asientos'=>true],
            ['codigo'=>'2.2.4',      'nombre'=>'Otras Cuentas por Pagar LP',                 'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.2',        'asientos'=>false],
            ['codigo'=>'2.2.4.1',    'nombre'=>'Prestamos de Accionistas LP',                'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.4',      'asientos'=>true],
            ['codigo'=>'2.2.4.2',    'nombre'=>'Pasivos por Arrendamientos LP',              'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.4',      'asientos'=>true],
            ['codigo'=>'2.2.5',      'nombre'=>'Provisiones a Largo Plazo',                  'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.2',        'asientos'=>false],
            ['codigo'=>'2.2.5.1',    'nombre'=>'Provision Jubilacion Patronal',              'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.5',      'asientos'=>true],
            ['codigo'=>'2.2.5.2',    'nombre'=>'Provision para Desahucio',                   'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.5',      'asientos'=>true],
            ['codigo'=>'2.2.5.3',    'nombre'=>'Provision por Garantias de Productos',       'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.5',      'asientos'=>true],
            ['codigo'=>'2.2.5.4',    'nombre'=>'Provision por Litigios y Demandas',          'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.5',      'asientos'=>true],
            ['codigo'=>'2.2.6',      'nombre'=>'Pasivos Diferidos',                          'tipo'=>'pasivo',     'nivel'=>3, 'padre'=>'2.2',        'asientos'=>false],
            ['codigo'=>'2.2.6.1',    'nombre'=>'Pasivo por Impuesto Diferido',               'tipo'=>'pasivo',     'nivel'=>4, 'padre'=>'2.2.6',      'asientos'=>true],

            // ── PATRIMONIO ───────────────────────────────────────────────────────
            ['codigo'=>'3',          'nombre'=>'PATRIMONIO',                                 'tipo'=>'patrimonio', 'nivel'=>1, 'padre'=>null,        'asientos'=>false],
            ['codigo'=>'3.1',        'nombre'=>'PATRIMONIO NETO',                            'tipo'=>'patrimonio', 'nivel'=>2, 'padre'=>'3',          'asientos'=>false],
            ['codigo'=>'3.1.1',      'nombre'=>'Capital',                                    'tipo'=>'patrimonio', 'nivel'=>3, 'padre'=>'3.1',        'asientos'=>false],
            ['codigo'=>'3.1.1.01',   'nombre'=>'Capital Suscrito o Asignado',                'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.1',      'asientos'=>true],
            ['codigo'=>'3.1.1.02',   'nombre'=>'(-) Capital Suscrito No Pagado',             'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.1',      'asientos'=>true],
            ['codigo'=>'3.1.2',      'nombre'=>'Reservas',                                   'tipo'=>'patrimonio', 'nivel'=>3, 'padre'=>'3.1',        'asientos'=>false],
            ['codigo'=>'3.1.2.01',   'nombre'=>'Reserva Legal',                              'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.2',      'asientos'=>true],
            ['codigo'=>'3.1.2.02',   'nombre'=>'Reservas Facultativas',                      'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.2',      'asientos'=>true],
            ['codigo'=>'3.1.2.03',   'nombre'=>'Reservas Estatutarias',                      'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.2',      'asientos'=>true],
            ['codigo'=>'3.1.3',      'nombre'=>'Otros Resultados Integrales',                'tipo'=>'patrimonio', 'nivel'=>3, 'padre'=>'3.1',        'asientos'=>false],
            ['codigo'=>'3.1.3.01',   'nombre'=>'Superavit por Revaluacion PPE',              'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.3',      'asientos'=>true],
            ['codigo'=>'3.1.3.02',   'nombre'=>'Ganancias y Perdidas Actuariales',           'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.3',      'asientos'=>true],
            ['codigo'=>'3.1.4',      'nombre'=>'Resultados Acumulados',                      'tipo'=>'patrimonio', 'nivel'=>3, 'padre'=>'3.1',        'asientos'=>false],
            ['codigo'=>'3.1.4.01',   'nombre'=>'Ganancias Acumuladas',                       'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.4',      'asientos'=>true],
            ['codigo'=>'3.1.4.02',   'nombre'=>'(-) Perdidas Acumuladas',                    'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.4',      'asientos'=>true],
            ['codigo'=>'3.1.4.03',   'nombre'=>'Resultados Acumulados NIIF',                 'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.4',      'asientos'=>true],
            ['codigo'=>'3.1.5',      'nombre'=>'Resultados del Periodo',                     'tipo'=>'patrimonio', 'nivel'=>3, 'padre'=>'3.1',        'asientos'=>false],
            ['codigo'=>'3.1.5.01',   'nombre'=>'Utilidad del Periodo',                       'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.5',      'asientos'=>true],
            ['codigo'=>'3.1.5.02',   'nombre'=>'(-) Perdida del Periodo',                    'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.5',      'asientos'=>true],
            ['codigo'=>'3.1.6',      'nombre'=>'Aportes de Socios',                          'tipo'=>'patrimonio', 'nivel'=>3, 'padre'=>'3.1',        'asientos'=>false],
            ['codigo'=>'3.1.6.01',   'nombre'=>'Aportes para Futuras Capitalizaciones',      'tipo'=>'patrimonio', 'nivel'=>4, 'padre'=>'3.1.6',      'asientos'=>true],

            // ── INGRESOS ─────────────────────────────────────────────────────────
            ['codigo'=>'4',          'nombre'=>'INGRESOS',                                   'tipo'=>'ingreso',    'nivel'=>1, 'padre'=>null,        'asientos'=>false],
            ['codigo'=>'4.1',        'nombre'=>'Ingresos de Actividades Ordinarias',         'tipo'=>'ingreso',    'nivel'=>2, 'padre'=>'4',          'asientos'=>false],
            ['codigo'=>'4.1.1',      'nombre'=>'Venta de Bienes',                            'tipo'=>'ingreso',    'nivel'=>3, 'padre'=>'4.1',        'asientos'=>false],
            ['codigo'=>'4.1.1.01',   'nombre'=>'Venta de Mercancias Locales',                'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.1.1',      'asientos'=>true],
            ['codigo'=>'4.1.1.02',   'nombre'=>'Venta de Mercancias al Exterior',            'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.1.1',      'asientos'=>true],
            ['codigo'=>'4.1.2',      'nombre'=>'Prestacion de Servicios',                    'tipo'=>'ingreso',    'nivel'=>3, 'padre'=>'4.1',        'asientos'=>false],
            ['codigo'=>'4.1.2.01',   'nombre'=>'Ingresos por Servicios Tecnicos',            'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.1.2',      'asientos'=>true],
            ['codigo'=>'4.1.2.02',   'nombre'=>'Ingresos por Capacitacion y Asesorias',      'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.1.2',      'asientos'=>true],
            ['codigo'=>'4.1.3',      'nombre'=>'(-) Descuentos y Devoluciones',              'tipo'=>'ingreso',    'nivel'=>3, 'padre'=>'4.1',        'asientos'=>false],
            ['codigo'=>'4.1.3.01',   'nombre'=>'(-) Devoluciones en Ventas',                 'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.1.3',      'asientos'=>true],
            ['codigo'=>'4.1.3.02',   'nombre'=>'(-) Descuentos y Rebajas en Ventas',         'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.1.3',      'asientos'=>true],
            ['codigo'=>'4.2',        'nombre'=>'Otros Ingresos No Operacionales',            'tipo'=>'ingreso',    'nivel'=>2, 'padre'=>'4',          'asientos'=>false],
            ['codigo'=>'4.2.1',      'nombre'=>'Otros Ingresos',                             'tipo'=>'ingreso',    'nivel'=>3, 'padre'=>'4.2',        'asientos'=>false],
            ['codigo'=>'4.2.1.01',   'nombre'=>'Ingresos Financieros',                       'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.2.1',      'asientos'=>true],
            ['codigo'=>'4.2.1.02',   'nombre'=>'Ganancia en Venta de PPE',                   'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.2.1',      'asientos'=>true],
            ['codigo'=>'4.2.1.03',   'nombre'=>'Ingresos por Arrendamientos',                'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.2.1',      'asientos'=>true],
            ['codigo'=>'4.2.1.09',   'nombre'=>'Otros Ingresos Varios',                      'tipo'=>'ingreso',    'nivel'=>4, 'padre'=>'4.2.1',      'asientos'=>true],

            // ── GASTOS ───────────────────────────────────────────────────────────
            ['codigo'=>'5',          'nombre'=>'GASTOS',                                     'tipo'=>'gasto',      'nivel'=>1, 'padre'=>null,        'asientos'=>false],
            ['codigo'=>'5.1',        'nombre'=>'COSTO DE VENTAS Y PRODUCCION',               'tipo'=>'gasto',      'nivel'=>2, 'padre'=>'5',          'asientos'=>false],
            ['codigo'=>'5.1.1.1',    'nombre'=>'Costo de Ventas Mercancias Locales',         'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.1',        'asientos'=>true],
            ['codigo'=>'5.1.1.2',    'nombre'=>'Costo de Ventas Mercancias Importadas',      'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.1',        'asientos'=>true],
            ['codigo'=>'5.1.1.3',    'nombre'=>'Costo de Prestacion de Servicios',           'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.1',        'asientos'=>true],
            ['codigo'=>'5.1.1.4',    'nombre'=>'Ajustes por Faltantes o Mermas',             'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.1',        'asientos'=>true],
            ['codigo'=>'5.2',        'nombre'=>'GASTOS OPERATIVOS',                          'tipo'=>'gasto',      'nivel'=>2, 'padre'=>'5',          'asientos'=>false],
            ['codigo'=>'5.2.1',      'nombre'=>'Gastos de Personal',                         'tipo'=>'gasto',      'nivel'=>3, 'padre'=>'5.2',        'asientos'=>false],
            ['codigo'=>'5.2.1.01',   'nombre'=>'Sueldos y Salarios',                         'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.02',   'nombre'=>'Horas Extras y Suplementarias',              'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.03',   'nombre'=>'Comisiones y Bonos',                         'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.04',   'nombre'=>'Aporte Patronal IESS 11.15%',                'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.05',   'nombre'=>'Decimo Tercer Sueldo',                       'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.06',   'nombre'=>'Decimo Cuarto Sueldo',                       'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.07',   'nombre'=>'Vacaciones',                                 'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.08',   'nombre'=>'Fondos de Reserva',                          'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.09',   'nombre'=>'Capacitacion al Personal',                   'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.1.10',   'nombre'=>'Uniformes y Equipos de Proteccion',          'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.1',      'asientos'=>true],
            ['codigo'=>'5.2.2',      'nombre'=>'Gastos Generales y Administrativos',         'tipo'=>'gasto',      'nivel'=>3, 'padre'=>'5.2',        'asientos'=>false],
            ['codigo'=>'5.2.2.01',   'nombre'=>'Honorarios Profesionales',                   'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.02',   'nombre'=>'Arrendamientos de Locales',                  'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.03',   'nombre'=>'Servicios Basicos',                          'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.04',   'nombre'=>'Mantenimiento de Instalaciones',             'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.05',   'nombre'=>'Mantenimiento de Vehiculos',                 'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.06',   'nombre'=>'Suministros de Oficina',                     'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.07',   'nombre'=>'Gastos de Viaje y Viaticos',                 'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.08',   'nombre'=>'Combustibles y Lubricantes',                 'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.09',   'nombre'=>'Seguros de Vehiculos y Mercaderia',          'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.10',   'nombre'=>'Impuestos, Tasas y Contribuciones',          'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.2.11',   'nombre'=>'Publicidad y Marketing',                     'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.2',      'asientos'=>true],
            ['codigo'=>'5.2.3',      'nombre'=>'Gastos de Depreciacion y Amortizacion',      'tipo'=>'gasto',      'nivel'=>3, 'padre'=>'5.2',        'asientos'=>false],
            ['codigo'=>'5.2.3.01',   'nombre'=>'Depreciacion de PPE',                        'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.3',      'asientos'=>true],
            ['codigo'=>'5.2.3.02',   'nombre'=>'Amortizacion de Intangibles',                'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.3',      'asientos'=>true],
            ['codigo'=>'5.2.4',      'nombre'=>'Gastos por Provisiones',                     'tipo'=>'gasto',      'nivel'=>3, 'padre'=>'5.2',        'asientos'=>false],
            ['codigo'=>'5.2.4.01',   'nombre'=>'Gasto por Cuentas Incobrables',              'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.4',      'asientos'=>true],
            ['codigo'=>'5.2.4.02',   'nombre'=>'Gasto Provision Jubilacion y Desahucio',     'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.2.4',      'asientos'=>true],
            ['codigo'=>'5.3',        'nombre'=>'GASTOS FINANCIEROS',                         'tipo'=>'gasto',      'nivel'=>2, 'padre'=>'5',          'asientos'=>false],
            ['codigo'=>'5.3.1.01',   'nombre'=>'Intereses por Prestamos Bancarios',          'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.3',        'asientos'=>true],
            ['codigo'=>'5.3.1.02',   'nombre'=>'Comisiones Bancarias y Pasarelas de Pago',   'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.3',        'asientos'=>true],
            ['codigo'=>'5.3.1.03',   'nombre'=>'Diferencia en Cambio',                       'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.3',        'asientos'=>true],
            ['codigo'=>'5.4',        'nombre'=>'OTROS GASTOS Y NO DEDUCIBLES',               'tipo'=>'gasto',      'nivel'=>2, 'padre'=>'5',          'asientos'=>false],
            ['codigo'=>'5.4.1.01',   'nombre'=>'Gastos No Deducibles Locales',               'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.4',        'asientos'=>true],
            ['codigo'=>'5.4.1.02',   'nombre'=>'Perdida en Venta de Activos Fijos',          'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.4',        'asientos'=>true],
            ['codigo'=>'5.4.1.03',   'nombre'=>'Otros Gastos Extraordinarios',               'tipo'=>'gasto',      'nivel'=>4, 'padre'=>'5.4',        'asientos'=>true],
        ];
    }
}
